// Domain-to-source-name mapping for display alongside bylines.
// Add entries as new domains appear in the feed.

const DOMAIN_MAP = {
  'bbc.co.uk': 'BBC',
  'www.bbc.co.uk': 'BBC',
  'bbc.com': 'BBC',
  'www.bbc.com': 'BBC',
  'bbci.co.uk': 'BBC',
  'feeds.bbci.co.uk': 'BBC',
  'theguardian.com': 'The Guardian',
  'www.theguardian.com': 'The Guardian',
  'guardianapis.com': 'The Guardian',
  'belfastlive.co.uk': 'Belfast Live',
  'www.belfastlive.co.uk': 'Belfast Live',
  'bernama.com': 'Bernama',
  'www.bernama.com': 'Bernama',
  'brisbanetimes.com.au': 'Brisbane Times',
  'www.brisbanetimes.com.au': 'Brisbane Times',
  'businessinsider.com': 'Business Insider',
  'www.businessinsider.com': 'Business Insider',
  'dailymail.com': 'Daily Mail',
  'www.dailymail.com': 'Daily Mail',
  'dnaindia.com': 'DNA India',
  'www.dnaindia.com': 'DNA India',
  'economictimes.indiatimes.com': 'Economic Times',
  'edinburghnews.scotsman.com': 'Edinburgh News',
  'www.edinburghnews.scotsman.com': 'Edinburgh News',
  'guitarworld.com': 'Guitar World',
  'independent.co.uk': 'The Independent',
  'www.independent.co.uk': 'The Independent',
  'indiatoday.in': 'India Today',
  'www.indiatoday.in': 'India Today',
  'japantoday.com': 'Japan Today',
  'kark.com': 'KARK',
  'www.kark.com': 'KARK',
  'koreatimes.co.kr': 'Korea Times',
  'www.koreatimes.co.kr': 'Korea Times',
  'marieclaire.co.uk': "Marie Claire",
  'www.marieclaire.co.uk': "Marie Claire",
  'metro.co.uk': 'Metro',
  'mirror.co.uk': 'Mirror',
  'www.mirror.co.uk': 'Mirror',
  'nakedcapitalism.com': 'Naked Capitalism',
  'www.nakedcapitalism.com': 'Naked Capitalism',
  'nltimes.nl': 'NL Times',
  'scotsman.com': 'The Scotsman',
  'standard.co.uk': 'Evening Standard',
  'www.standard.co.uk': 'Evening Standard',
  'swarajyamag.com': 'Swarajya',
  'tass.com': 'TASS',
  'theage.com.au': 'The Age',
  'www.theage.com.au': 'The Age',
  'thewest.com.au': 'The West Australian',
  'tmz.com': 'TMZ',
  'www.tmz.com': 'TMZ',
  'twelfthmagpie.com': 'Twelfth Magpie',
  'walesonline.co.uk': 'Wales Online',
  'www.walesonline.co.uk': 'Wales Online',
  // Tech publishers (surfaced via Techmeme aggregation)
  'techcrunch.com': 'TechCrunch',
  'www.techcrunch.com': 'TechCrunch',
  'theverge.com': 'The Verge',
  'www.theverge.com': 'The Verge',
  'arstechnica.com': 'Ars Technica',
  'feeds.arstechnica.com': 'Ars Technica',
  'wired.com': 'Wired',
  'www.wired.com': 'Wired',
  'bloomberg.com': 'Bloomberg',
  'www.bloomberg.com': 'Bloomberg',
  'businessinsider.com': 'Business Insider',
  'reuters.com': 'Reuters',
  'www.reuters.com': 'Reuters',
  'nytimes.com': 'New York Times',
  'www.nytimes.com': 'New York Times',
  'theinformation.com': 'The Information',
  'www.theinformation.com': 'The Information',
  'cnbc.com': 'CNBC',
  'www.cnbc.com': 'CNBC',
  'axios.com': 'Axios',
  'www.axios.com': 'Axios',
  'variety.com': 'Variety',
  'www.variety.com': 'Variety',
  'fastcompany.com': 'Fast Company',
  'www.fastcompany.com': 'Fast Company',
  'engadget.com': 'Engadget',
  'www.engadget.com': 'Engadget',
  'cnet.com': 'CNET',
  'www.cnet.com': 'CNET',
  'technologyreview.com': 'MIT Tech Review',
  'www.technologyreview.com': 'MIT Tech Review',
  'theatlantic.com': 'The Atlantic',
  'www.theatlantic.com': 'The Atlantic',
  'politico.com': 'Politico',
  'www.politico.com': 'Politico',
  'wsj.com': 'Wall Street Journal',
  'www.wsj.com': 'Wall Street Journal',
  'ft.com': 'Financial Times',
  'www.ft.com': 'Financial Times',
  'apnews.com': 'AP News',
  'www.apnews.com': 'AP News',
  'washingtontimes.com': 'Washington Times',
  'www.washingtontimes.com': 'Washington Times',
  'washingtonpost.com': 'Washington Post',
  'www.washingtonpost.com': 'Washington Post',
  'semafor.com': 'Semafor',
  'www.semafor.com': 'Semafor',
  'statnews.com': 'STAT News',
  'www.statnews.com': 'STAT News',
  'techmeme.com': 'Techmeme',
  'www.techmeme.com': 'Techmeme',
};

export function getSourceName(url) {
  if (!url) return null;
  try {
    const hostname = new URL(url).hostname;
    return DOMAIN_MAP[hostname] || null;
  } catch {
    return null;
  }
}
